language: python
python:
  - 2.7
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U pip wheel
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt
  - pip install https://github.com/hasgeek/coaster/archive/master.zip
  - npm install casperjs
env:
  - FLASK_ENV=testing
script:
  - ./runtests.sh
# after_success:
#   - coveralls
addons:
  postgresql: "9.4"
services:
  - redis-server
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
